server:
  port: 8888
spring:
  application:
    name: configuration-service
  cloud:
    config:
      server:
        git:
          uri: file:/home/fernando/Desktop/prueba-farmatodo/configuration-files 